In [30]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/sample_data/House_Prices_Dataset.csv")

df.head()

   location  square_feet  bedrooms  year_built   price
0   Tomball         3741         4        1972  584373
1      Katy         3252         5        1980  520567
2    Spring         1877         3        2011  296570
3  Pearland         1244         3        2006  201681
4   Tomball         2894         3        2019  469234

In [31]:
# unique locations
len(df["location"].unique())

10

In [32]:
# create dummy columns one-hot encoding
#df_encoded = pd.get_dummies(df, columns=["location"], drop_first=True)
#df_encoded


# label encoding
le = LabelEncoder()

df["location_encoded"] = le.fit_transform(df["location"])
df_encoded = df.drop("location", axis=1)
df_encoded

       square_feet  bedrooms  year_built   price  location_encoded
0             3741         4        1972  584373                 9
1             3252         5        1980  520567                 3
2             1877         3        2011  296570                 6
3             1244         3        2006  201681                 5
4             2894         3        2019  469234                 9
...            ...       ...         ...     ...               ...
19995         2385         4        1979  378211                 1
19996         3907         5        1997  656646                 1
19997         2116         2        1974  317544                 7
19998         1133         5        1973  184356                 1
19999         2227         2        1961  307742                 1

[20000 rows x 5 columns]

In [33]:
# df.drop will return a brand new data frame which will be assigned to X. This will not change the existing dataframe (df).
# unless you use inplace=True which will modify the existing dataframe (df).
X = df_encoded.drop("price", axis=1)
y = df_encoded["price"]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
model = LinearRegression()

In [36]:
# when you call fit the model is training...
model.fit(X_train, y_train)

LinearRegression()

In [37]:
y_pred = model.predict(X_test)

In [38]:
y_pred

array([349637.0217124 , 404874.24907354, 220421.26208269, ...,
       577702.64747699, 518810.5448814 , 418882.52274214])

In [39]:
from sklearn.metrics import mean_squared_error, r2_score

In [40]:
# Evaluate
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

Mean Squared Error: 224727333.19525298
R² Score: 0.9870314645864156

In [41]:
import numpy as np
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 14990.908351239194